# Generated by Django 3.0.4 on 2020-04-16 02:50

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('ver_en_web', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=30)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descuento', models.PositiveSmallIntegerField(null=True)),
                ('ver_descuento', models.BooleanField(default=True)),
                ('ver_en_web', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_total', models.PositiveSmallIntegerField(default=0)),
                ('observaciones', models.TextField(null=True)),
                ('estado', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(null=True)),
                ('porcentaje', models.PositiveSmallIntegerField(default=0)),
                ('servicio_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServiciosCliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descuento', models.PositiveSmallIntegerField(null=True)),
                ('ver_descuento', models.BooleanField(default=True)),
                ('ver_en_web', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='FotoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ver_en_web', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=core.models.path_and_rename)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='FotoSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ver_en_web', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=core.models.path_and_rename)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ver_en_web', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=core.models.path_and_rename)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicios',
            field=models.ManyToManyField(through='core.ServiciosCliente', to='core.Servicio'),
        ),
    ]
