# Generated by Django 3.0.4 on 2020-04-04 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_ver_en_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='descripcion',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
