# Generated by Django 3.0.4 on 2020-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200404_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
