# Generated by Django 3.0.4 on 2020-04-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200404_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fotos',
        ),
    ]
