# Generated by Django 3.0.4 on 2020-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicio_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descuento',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ver_descuento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ver_en_web',
            field=models.BooleanField(default=True),
        ),
    ]
